enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "anddea/revanced-patches"
remove-rv-integrations-checks = true
#patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced eXtended"
patches-version = "dev" # 'latest', 'dev', or a version number. default: "latest"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"                                                   
excluded-patches = ""                                                 
included-patches = "" 
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='yt.rvx.tdc' "
version = "20.13.41"                                                      
exclusive-patches = false                                             
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"
